// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djnvyypnmyhalpvesgnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqbnZ5eXBubXloYWxwdmVzZ25iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NjUxOTMsImV4cCI6MjA3MjI0MTE5M30.OpCBbAVqbxroqFn3FXcDsajC3Z7hqzZdjZZUvdtZWzU";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});